import type { NVDAPlaywright } from "@guidepup/playwright";
import { expect } from "@playwright/test";

/** Waits for automatic speech generated by an action; it never navigates to a live region. */
export async function expectSpokenAfterAction(
  nvda: NVDAPlaywright,
  action: () => Promise<void>,
  phrase: string | RegExp,
  timeout = 5000,
): Promise<string> {
  await nvda.perform(nvda.keyboardCommands.stopSpeech);
  await nvda.clearSpokenPhraseLog();
  await action();
  const deadline = Date.now() + timeout;
  let log: string[] = [];
  do {
    log = await nvda.spokenPhraseLog();
    const spoken = log.join(" ");
    if (typeof phrase === "string" ? spoken.includes(phrase) : phrase.test(spoken)) {
      await new Promise((resolve) => setTimeout(resolve, 750));
      log = await nvda.spokenPhraseLog();
      const stableSpeech = log.join(" ");
      const matches =
        typeof phrase === "string"
          ? stableSpeech.split(phrase).length - 1
          : [
              ...stableSpeech.matchAll(
                new RegExp(phrase.source, `${phrase.flags.replace("g", "")}g`),
              ),
            ].length;
      expect(matches, `Expected one automatic utterance. Full log: ${stableSpeech}`).toBe(1);
      return stableSpeech;
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
  } while (Date.now() < deadline);
  expect(
    log.join(" "),
    `Automatic NVDA speech did not contain ${String(phrase)}. Full log:`,
  ).toMatch(
    typeof phrase === "string" ? new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")) : phrase,
  );
  return log.join(" ");
}
