import type { NVDAPlaywright } from "@guidepup/playwright";
import { expect } from "@playwright/test";

/** Waits for automatic speech generated by an action; it never navigates to a live region. */
export async function expectSpokenAfterAction(
  nvda: NVDAPlaywright,
  action: () => Promise<void>,
  phrase: string | RegExp,
  timeout = 5000,
): Promise<void> {
  await nvda.clearSpokenPhraseLog();
  await action();
  const deadline = Date.now() + timeout;
  let log: string[] = [];
  do {
    log = await nvda.spokenPhraseLog();
    const spoken = log.join(" ");
    if (typeof phrase === "string" ? spoken.includes(phrase) : phrase.test(spoken)) return;
    await new Promise((resolve) => setTimeout(resolve, 100));
  } while (Date.now() < deadline);
  expect(
    log.join(" "),
    `Automatic NVDA speech did not contain ${String(phrase)}. Full log:`,
  ).toMatch(
    typeof phrase === "string" ? new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")) : phrase,
  );
}
